server:
  port: 9130
  servlet:
    contextPath: /ggt


spring:
  #  profiles:
  #    active: dev

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greedy_ghost_token
    username: shakir
    password: "Apple#1M"

  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: validate #create|update|create-drop|validate|none
      generate-ddl: false

logging:
  file:
    name: D:\ajaxer-org\logs\ggt.log
  level:
    org:
      ajaxer:
        tgb: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10


ghost:
  dailyTokenTime: 22 # in hours
  allowedOriginPattern: "https://rr5h5z3r-9131.inc1.devtunnels.ms/"

telegram:
  bot:
    token: 5901451996:AAGe8LRa3cGbYZvjHTSf69Rcw5kv7xoUu_0
    username: ajaxer_test_bot

jobs:
  requestJob:
    cron: "* * * * * *" # every second
  dailyReferralCommissionJob:
    cron: "0 0 1 * * *" # every day 1am
    maxResultPerPage: 100
    commissionPercentage: 10

