name: Maven Clean Package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  code-build:
    name: Maven Clean Package
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:17-mvn3

    steps:

      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true --file pom.xml --no-transfer-progress

